language: python
sudo: false

env:
  global:
    - PIP_DEPS="pytest coveralls pytest-cov flake8"

python:
  - '3.5'
  - '3.6'


install:
- travis_retry pip install $PIP_DEPS
- travis_retry pip install -r requirements.txt
- travis_retry pip install -e .

script:
  - pytest


# File based off .yml file by McFee and Kell
https://github.com/bmcfee/ismir2018-oss-tutorial/blob/master/.travis.yml
